version: '3.8'
services:
  myDb:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: docker_test
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - D:/DockerDB:/var/lib/mysql #desiredDBStoragePath:fixedMySqlPath
  app:
    image: app:latest
    ports:
      - 9695:9695
    build: .
    restart: always
    environment:
      MYSQL_HOST: myDb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    depends_on:
      - myDb
